; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=sparc-unknown-linux-gnu | FileCheck %s --check-prefixes=SPARC
; RUN: llc < %s -mtriple=sparc64-unknown-linux-gnu | FileCheck %s --check-prefixes=SPARC64

define { i128, i8 } @muloti_test(i128 %l, i128 %r) unnamed_addr #0 {
; SPARC-LABEL: muloti_test:
; SPARC:         .cfi_startproc
; SPARC-NEXT:  ! %bb.0: ! %start
; SPARC-NEXT:    save %sp, -120, %sp
; SPARC-NEXT:    .cfi_def_cfa_register %fp
; SPARC-NEXT:    .cfi_window_save
; SPARC-NEXT:    .cfi_register 15, 31
; SPARC-NEXT:    ld [%fp+92], %l0
; SPARC-NEXT:    ld [%fp+96], %g1
; SPARC-NEXT:    umul %i2, %i5, %g2
; SPARC-NEXT:    rd %y, %g3
; SPARC-NEXT:    st %g3, [%fp+-12] ! 4-byte Folded Spill
; SPARC-NEXT:    umul %i4, %i3, %g3
; SPARC-NEXT:    rd %y, %g4
; SPARC-NEXT:    st %g4, [%fp+-20] ! 4-byte Folded Spill
; SPARC-NEXT:    st %g1, [%sp+96]
; SPARC-NEXT:    umul %i5, %i3, %g4
; SPARC-NEXT:    rd %y, %l3
; SPARC-NEXT:    st %l0, [%sp+92]
; SPARC-NEXT:    umul %l0, %i1, %l0
; SPARC-NEXT:    rd %y, %l1
; SPARC-NEXT:    st %l1, [%fp+-4] ! 4-byte Folded Spill
; SPARC-NEXT:    add %g3, %g2, %l2
; SPARC-NEXT:    umul %i0, %g1, %g2
; SPARC-NEXT:    rd %y, %g3
; SPARC-NEXT:    st %g3, [%fp+-8] ! 4-byte Folded Spill
; SPARC-NEXT:    add %l3, %l2, %l4
; SPARC-NEXT:    umul %i1, %g1, %g1
; SPARC-NEXT:    rd %y, %l7
; SPARC-NEXT:    add %g2, %l0, %g2
; SPARC-NEXT:    st %g2, [%fp+-16] ! 4-byte Folded Spill
; SPARC-NEXT:    add %l7, %g2, %l1
; SPARC-NEXT:    addcc %g1, %g4, %l6
; SPARC-NEXT:    mov 0, %l0
; SPARC-NEXT:    addxcc %l1, %l4, %l5
; SPARC-NEXT:    mov %l0, %o0
; SPARC-NEXT:    mov %l0, %o1
; SPARC-NEXT:    mov %i2, %o2
; SPARC-NEXT:    mov %i3, %o3
; SPARC-NEXT:    mov %l0, %o4
; SPARC-NEXT:    call __multi3
; SPARC-NEXT:    mov %l0, %o5
; SPARC-NEXT:    addcc %o1, %l6, %g2
; SPARC-NEXT:    addxcc %o0, %l5, %g1
; SPARC-NEXT:    mov 1, %g3
; SPARC-NEXT:    cmp %g1, %o0
; SPARC-NEXT:    mov %o3, %i3
; SPARC-NEXT:    bcs .LBB0_2
; SPARC-NEXT:    mov %g3, %o3
; SPARC-NEXT:  ! %bb.1: ! %start
; SPARC-NEXT:    mov %l0, %o3
; SPARC-NEXT:  .LBB0_2: ! %start
; SPARC-NEXT:    cmp %g2, %o1
; SPARC-NEXT:    bcs .LBB0_4
; SPARC-NEXT:    mov %g3, %g4
; SPARC-NEXT:  ! %bb.3: ! %start
; SPARC-NEXT:    mov %l0, %g4
; SPARC-NEXT:  .LBB0_4: ! %start
; SPARC-NEXT:    cmp %g1, %o0
; SPARC-NEXT:    be,a .LBB0_11
; SPARC-NEXT:    xor %g1, %o0, %l5
; SPARC-NEXT:  ! %bb.5: ! %start
; SPARC-NEXT:    mov %o3, %g4
; SPARC-NEXT:  ! %bb.6: ! %start
; SPARC-NEXT:    xor %g1, %o0, %l5
; SPARC-NEXT:  .LBB0_11:
; SPARC-NEXT:    xor %g2, %o1, %l6
; SPARC-NEXT:    or %l6, %l5, %l5
; SPARC-NEXT:    cmp %g0, %l5
; SPARC-NEXT:    subxcc %g0, %g0, %o0
; SPARC-NEXT:    cmp %l4, %l3
; SPARC-NEXT:    bcs .LBB0_8
; SPARC-NEXT:    mov %g3, %l3
; SPARC-NEXT:  ! %bb.7: ! %start
; SPARC-NEXT:    mov %l0, %l3
; SPARC-NEXT:  .LBB0_8: ! %start
; SPARC-NEXT:    and %g4, %o0, %g4
; SPARC-NEXT:    cmp %g0, %l2
; SPARC-NEXT:    subxcc %g0, %g0, %l2
; SPARC-NEXT:    and %l3, %l2, %l2
; SPARC-NEXT:    cmp %g0, %i2
; SPARC-NEXT:    addxcc %g0, %g0, %i2
; SPARC-NEXT:    cmp %g0, %i4
; SPARC-NEXT:    addxcc %g0, %g0, %l3
; SPARC-NEXT:    and %l3, %i2, %i2
; SPARC-NEXT:    ld [%fp+-20], %l3 ! 4-byte Folded Reload
; SPARC-NEXT:    cmp %g0, %l3
; SPARC-NEXT:    addxcc %g0, %g0, %l3
; SPARC-NEXT:    or %i2, %l3, %i2
; SPARC-NEXT:    ld [%fp+-12], %l3 ! 4-byte Folded Reload
; SPARC-NEXT:    cmp %g0, %l3
; SPARC-NEXT:    addxcc %g0, %g0, %l3
; SPARC-NEXT:    or %i2, %l3, %i2
; SPARC-NEXT:    cmp %l1, %l7
; SPARC-NEXT:    bcs .LBB0_10
; SPARC-NEXT:    or %i2, %l2, %i2
; SPARC-NEXT:  ! %bb.9: ! %start
; SPARC-NEXT:    mov %l0, %g3
; SPARC-NEXT:  .LBB0_10: ! %start
; SPARC-NEXT:    ld [%fp+-16], %l0 ! 4-byte Folded Reload
; SPARC-NEXT:    cmp %g0, %l0
; SPARC-NEXT:    subxcc %g0, %g0, %l0
; SPARC-NEXT:    and %g3, %l0, %g3
; SPARC-NEXT:    ld [%fp+92], %l0
; SPARC-NEXT:    cmp %g0, %l0
; SPARC-NEXT:    addxcc %g0, %g0, %l0
; SPARC-NEXT:    cmp %g0, %i0
; SPARC-NEXT:    addxcc %g0, %g0, %l1
; SPARC-NEXT:    and %l1, %l0, %l0
; SPARC-NEXT:    ld [%fp+-8], %l1 ! 4-byte Folded Reload
; SPARC-NEXT:    cmp %g0, %l1
; SPARC-NEXT:    addxcc %g0, %g0, %l1
; SPARC-NEXT:    or %l0, %l1, %l0
; SPARC-NEXT:    ld [%fp+-4], %l1 ! 4-byte Folded Reload
; SPARC-NEXT:    cmp %g0, %l1
; SPARC-NEXT:    addxcc %g0, %g0, %l1
; SPARC-NEXT:    or %l0, %l1, %l0
; SPARC-NEXT:    or %l0, %g3, %g3
; SPARC-NEXT:    or %i5, %i4, %i4
; SPARC-NEXT:    cmp %g0, %i4
; SPARC-NEXT:    addxcc %g0, %g0, %i4
; SPARC-NEXT:    or %i1, %i0, %i0
; SPARC-NEXT:    cmp %g0, %i0
; SPARC-NEXT:    addxcc %g0, %g0, %i0
; SPARC-NEXT:    and %i0, %i4, %i0
; SPARC-NEXT:    or %i0, %g3, %i0
; SPARC-NEXT:    or %i0, %i2, %i0
; SPARC-NEXT:    or %i0, %g4, %i0
; SPARC-NEXT:    and %i0, 1, %i4
; SPARC-NEXT:    mov %g1, %i0
; SPARC-NEXT:    mov %g2, %i1
; SPARC-NEXT:    ret
; SPARC-NEXT:    restore %g0, %o2, %o2
;
; SPARC64-LABEL: muloti_test:
; SPARC64:         .cfi_startproc
; SPARC64-NEXT:  ! %bb.0: ! %start
; SPARC64-NEXT:    save %sp, -176, %sp
; SPARC64-NEXT:    .cfi_def_cfa_register %fp
; SPARC64-NEXT:    .cfi_window_save
; SPARC64-NEXT:    .cfi_register 15, 31
; SPARC64-NEXT:    srax %i2, 63, %o0
; SPARC64-NEXT:    srax %i1, 63, %o2
; SPARC64-NEXT:    mov %i2, %o1
; SPARC64-NEXT:    call __multi3
; SPARC64-NEXT:    mov %i1, %o3
; SPARC64-NEXT:    mov %o0, %i4
; SPARC64-NEXT:    mov %o1, %i5
; SPARC64-NEXT:    srax %i0, 63, %o0
; SPARC64-NEXT:    srax %i3, 63, %o2
; SPARC64-NEXT:    mov %i0, %o1
; SPARC64-NEXT:    call __multi3
; SPARC64-NEXT:    mov %i3, %o3
; SPARC64-NEXT:    mov %o0, %l0
; SPARC64-NEXT:    add %o1, %i5, %l1
; SPARC64-NEXT:    mov 0, %i5
; SPARC64-NEXT:    mov %i5, %o0
; SPARC64-NEXT:    mov %i1, %o1
; SPARC64-NEXT:    mov %i5, %o2
; SPARC64-NEXT:    call __multi3
; SPARC64-NEXT:    mov %i3, %o3
; SPARC64-NEXT:    add %o0, %l1, %i1
; SPARC64-NEXT:    cmp %i1, %o0
; SPARC64-NEXT:    mov %i5, %i3
; SPARC64-NEXT:    movcs %xcc, 1, %i3
; SPARC64-NEXT:    cmp %l1, 0
; SPARC64-NEXT:    move %xcc, 0, %i3
; SPARC64-NEXT:    cmp %i4, 0
; SPARC64-NEXT:    mov %i5, %i4
; SPARC64-NEXT:    movne %xcc, 1, %i4
; SPARC64-NEXT:    cmp %l0, 0
; SPARC64-NEXT:    mov %i5, %g1
; SPARC64-NEXT:    movne %xcc, 1, %g1
; SPARC64-NEXT:    cmp %i2, 0
; SPARC64-NEXT:    mov %i5, %i2
; SPARC64-NEXT:    movne %xcc, 1, %i2
; SPARC64-NEXT:    cmp %i0, 0
; SPARC64-NEXT:    movne %xcc, 1, %i5
; SPARC64-NEXT:    and %i5, %i2, %i0
; SPARC64-NEXT:    or %i0, %g1, %i0
; SPARC64-NEXT:    or %i0, %i4, %i0
; SPARC64-NEXT:    or %i0, %i3, %i0
; SPARC64-NEXT:    srl %i0, 0, %i2
; SPARC64-NEXT:    mov %i1, %i0
; SPARC64-NEXT:    ret
; SPARC64-NEXT:    restore %g0, %o1, %o1
start:
  %0 = tail call { i128, i1 } @llvm.umul.with.overflow.i128(i128 %l, i128 %r) #2
  %1 = extractvalue { i128, i1 } %0, 0
  %2 = extractvalue { i128, i1 } %0, 1
  %3 = zext i1 %2 to i8
  %4 = insertvalue { i128, i8 } undef, i128 %1, 0
  %5 = insertvalue { i128, i8 } %4, i8 %3, 1
  ret { i128, i8 } %5
}

; Function Attrs: nounwind readnone speculatable
declare { i128, i1 } @llvm.umul.with.overflow.i128(i128, i128) #1

attributes #0 = { nounwind readnone uwtable }
attributes #1 = { nounwind readnone speculatable }
attributes #2 = { nounwind }
